[package]
name = "app"
version = "0.1.0"
authors = ["John-Craig Borman <borman.johncraig@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
tui = { package = "ratatui", version = "0.21.0" }
api = { path = "../api" }
tokio = "1.33.0"
